project:
  type: website
  output-dir: docs

website:
  title: "Maximiliano Machado – PhD(c) Economics, Rotman School of Management, UofT"
  description: "Maximiliano Machado is interested in topics of Industrial Organization, Microeconomics and Applied Econometrics"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: research.qmd
      - text: "CV"
        href: cv_May2025.pdf 
