project:
  type: website
  output-dir: docs

website:
  title: "Maximiliano Machado"
  favicon: images/favicon.png
  navbar:
    background: white
    foreground: "#111"
    border: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "CV"
        href: cv_machado.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
